<?php

namespace Rushing\CompositionSpineData\Vocabulary;

use Rushing\CompositionSpineData\GenerationAttributesStrategy;
use Rushing\CompositionSpineData\KeywordVocabulary;
use Rushing\LaravelDataSchemas\Vocabulary\KeywordDescriptor;
use Rushing\LaravelDataSchemas\Vocabulary\KeywordVocabularyDescriber;
use Rushing\LaravelDataSchemas\Vocabulary\ValueSource;

/**
 * The composition generation-grammar VOCABULARY — the `x-swc-*` keyword dialect itself, as opposed to a
 * profile's grammar instance that *uses* it. This is composition's *content*: the describer *mechanism*
 * (reflect a value domain, render it to JSON Schema + TypeScript) lives in the base
 * {@see KeywordVocabularyDescriber}; here we supply only which keywords the vocabulary comprises, how to
 * resolve their (prefix-aware) strings, and its identity.
 *
 * The vocabulary is *derived*, never hand-authored, and composition describes only what it OWNS:
 *  - attribute-projected keywords come from {@see GenerationAttributesStrategy::bindings()} (the same source
 *    the emit path consumes), with each value domain reflected live — so a new enum case flows in with no
 *    edit here;
 *  - the read-side `max-depth` keyword (no attribute emits it) is declared by the engine.
 *
 * Base/standard keywords (the unprefixed `x-dereference`, owned by the `laravel-json-reference` leaf) are NOT
 * composition's to describe — their meaning lives with their owner. They are passed in as `$baseKeywords` and
 * unioned at the export composition point (which depends on both leaves); {@see keywordString()} still resolves
 * their unprefixed string through this engine's {@see KeywordVocabulary}.
 *
 * A coverage guard (test) asserts every keyword {@see KeywordVocabulary::engineKeywords()} names is described here.
 */
class GrammarVocabulary extends KeywordVocabularyDescriber
{
    private KeywordVocabulary $vocab;

    /** @var list<KeywordDescriptor> */
    private array $baseKeywords;

    /**
     * @param  iterable<KeywordDescriptor>  $baseKeywords  base/standard keywords owned by another leaf (e.g. the
     *                                                     json-reference `x-dereference`), unioned in at export
     */
    public function __construct(?KeywordVocabulary $vocab = null, iterable $baseKeywords = [])
    {
        $this->vocab = $vocab ?? KeywordVocabulary::shared();
        $this->baseKeywords = is_array($baseKeywords) ? array_values($baseKeywords) : iterator_to_array($baseKeywords, false);
    }

    protected function descriptors(): iterable
    {
        foreach (GenerationAttributesStrategy::bindings() as $binding) {
            foreach ($binding->keywords as $keyword) {
                yield $keyword;
            }
        }

        yield $this->maxDepthKeyword();

        yield from $this->baseKeywords;
    }

    protected function keywordString(KeywordDescriptor $keyword): string
    {
        $accessor = $keyword->accessor;

        return $this->vocab->{$accessor}();
    }

    protected function title(): string
    {
        return 'GenerationGrammarKeywords';
    }

    protected function description(): string
    {
        return 'The composition generation-grammar keyword vocabulary — the x-swc-* dialect a Composition Profile grammar carries. Each property is a keyword; a property schema may carry any subset of these.';
    }

    protected function generatedByComment(): string
    {
        return '// Generated by `php artisan composition:export-grammar` — do not hand-edit.';
    }

    /**
     * The engine read-side keyword composition owns that no generation attribute emits: the `max-depth`
     * recursion cap.
     */
    private function maxDepthKeyword(): KeywordDescriptor
    {
        return new KeywordDescriptor(
            accessor: 'maxDepth',
            source: ValueSource::Integer,
            description: 'Caps the recursion depth of grammar expansion at this subtree root; the interpreter clamps the effective depth to the engine cap and demotes an expandable beat at the ceiling. Read-side only — no attribute emits it.',
        );
    }
}
