<?php

namespace Rushing\CompositionSpineData\Vocabulary;

use Rushing\CompositionSpineData\GenerationAttributesStrategy;
use Rushing\CompositionSpineData\KeywordVocabulary;
use Rushing\LaravelDataSchemas\Vocabulary\KeywordDescriptor;
use Rushing\LaravelDataSchemas\Vocabulary\KeywordVocabularyDescriber;
use Rushing\LaravelDataSchemas\Vocabulary\ValueSource;

/**
 * The composition generation-grammar VOCABULARY — the `x-swc-*` keyword dialect itself, as opposed to a
 * profile's grammar instance that *uses* it. This is composition's *content*: the describer *mechanism*
 * (reflect a value domain, render it to JSON Schema + TypeScript) lives in the base
 * {@see KeywordVocabularyDescriber}; here we supply only which keywords the vocabulary comprises, how to
 * resolve their (prefix-aware) strings, and its identity.
 *
 * The vocabulary is *derived*, never hand-authored:
 *  - attribute-projected keywords come from {@see GenerationAttributesStrategy::bindings()} (the same source
 *    the emit path consumes), with each value domain reflected live — so a new enum case flows in with no
 *    edit here;
 *  - the read-side `max-depth` keyword (no attribute emits it) is declared by the engine;
 *  - the base, unprefixed `x-dereference` keyword is named via {@see KeywordVocabulary} (canonical home: the
 *    `rushing/laravel-json-reference` leaf), described as base-owned/cross-engine.
 *
 * A coverage guard (test) asserts every keyword {@see KeywordVocabulary::keywords()} names is described here.
 */
class GrammarVocabulary extends KeywordVocabularyDescriber
{
    private KeywordVocabulary $vocab;

    public function __construct(?KeywordVocabulary $vocab = null)
    {
        $this->vocab = $vocab ?? KeywordVocabulary::shared();
    }

    protected function descriptors(): iterable
    {
        foreach (GenerationAttributesStrategy::bindings() as $binding) {
            foreach ($binding->keywords as $keyword) {
                yield $keyword;
            }
        }

        yield from $this->engineAndBaseKeywords();
    }

    protected function keywordString(KeywordDescriptor $keyword): string
    {
        $accessor = $keyword->accessor;

        return $this->vocab->{$accessor}();
    }

    protected function title(): string
    {
        return 'GenerationGrammarKeywords';
    }

    protected function description(): string
    {
        return 'The composition generation-grammar keyword vocabulary — the x-swc-* dialect a Composition Profile grammar carries. Each property is a keyword; a property schema may carry any subset of these.';
    }

    protected function generatedByComment(): string
    {
        return '// Generated by `php artisan composition:export-grammar` — do not hand-edit.';
    }

    /**
     * The keywords composition owns that no generation attribute emits: the engine read-side `max-depth`
     * cap, and the base, unprefixed `x-dereference` dispatch handle.
     *
     * @return list<KeywordDescriptor>
     */
    private function engineAndBaseKeywords(): array
    {
        return [
            new KeywordDescriptor(
                accessor: 'maxDepth',
                source: ValueSource::Integer,
                description: 'Caps the recursion depth of grammar expansion at this subtree root; the interpreter clamps the effective depth to the engine cap and demotes an expandable beat at the ceiling. Read-side only — no attribute emits it.',
            ),
            new KeywordDescriptor(
                accessor: 'dereference',
                source: ValueSource::Text,
                description: 'Base-owned, unprefixed dispatch handle (like $ref): names the Dereferencer that resolves this node. Shared across engines; canonical home is the laravel-json-reference leaf.',
            ),
        ];
    }
}
