<?php

namespace Rushing\CompositionSpineData\Vocabulary;

use ReflectionMethod;
use ReflectionNamedType;
use ReflectionParameter;
use ReflectionUnionType;
use RuntimeException;
use Rushing\CompositionSpineData\GenerationAttributesStrategy;
use Rushing\CompositionSpineData\KeywordVocabulary;

/**
 * The composition generation-grammar VOCABULARY — the `x-swc-*` keyword dialect itself, as opposed to a
 * profile's grammar instance that *uses* it. Assembled from its real owners and projected to a JSON-Schema
 * meta-schema + TypeScript so satellites, SDKs, and docs can pin the grammar without running the platform.
 *
 * The vocabulary is *derived*, never hand-authored:
 *  - attribute-projected keywords come from {@see GenerationAttributesStrategy::bindings()} (the same source
 *    the emit path consumes), with each value domain reflected live (enum `::cases()`, a `string|bool`
 *    return type, a constructor shape) — so a new enum case flows in with no edit here;
 *  - the read-side `max-depth` keyword (no attribute emits it) is declared by the engine;
 *  - the base, unprefixed `x-dereference` keyword is named via {@see KeywordVocabulary} (canonical home: the
 *    `rushing/laravel-json-reference` leaf), described as base-owned/cross-engine.
 *
 * A coverage guard (test) asserts every keyword {@see KeywordVocabulary::keywords()} names is described here.
 */
class GrammarVocabulary
{
    private KeywordVocabulary $vocab;

    public function __construct(?KeywordVocabulary $vocab = null)
    {
        $this->vocab = $vocab ?? KeywordVocabulary::shared();
    }

    /**
     * Every described keyword, keyed by its KeywordVocabulary accessor — the attribute-projected keywords
     * plus the engine read-side and base keywords no attribute emits.
     *
     * @return array<string, GenerationKeyword>
     */
    public function keywords(): array
    {
        $keywords = [];

        foreach (GenerationAttributesStrategy::bindings() as $binding) {
            foreach ($binding->keywords as $keyword) {
                $keywords[$keyword->accessor] = $keyword;
            }
        }

        foreach ($this->engineAndBaseKeywords() as $keyword) {
            $keywords[$keyword->accessor] = $keyword;
        }

        return $keywords;
    }

    /**
     * The vocabulary as a JSON-Schema meta-schema: an object whose properties ARE the keywords, each carrying
     * its reflected value domain and one-line description. Keys are the live (prefixed) keyword strings, sorted
     * for a stable, diff-friendly artifact.
     *
     * @return array<string, mixed>
     */
    public function toJsonSchema(): array
    {
        $properties = [];

        foreach ($this->keywords() as $keyword) {
            $name = $this->keywordString($keyword);
            $properties[$name] = ['description' => $keyword->description] + $this->jsonSchemaFor($keyword);
        }

        ksort($properties);

        return [
            '$schema' => 'https://json-schema.org/draft/2020-12/schema',
            'title' => 'GenerationGrammarKeywords',
            'description' => 'The composition generation-grammar keyword vocabulary — the x-swc-* dialect a Composition Profile grammar carries. Each property is a keyword; a property schema may carry any subset of these.',
            'type' => 'object',
            'properties' => $properties,
        ];
    }

    /**
     * The vocabulary as TypeScript: the named value types (enum unions, the cache-policy object) followed by a
     * `GenerationGrammarKeywords` interface whose optional members are the keyword strings.
     */
    public function toTypeScript(): string
    {
        $definitions = [];
        $members = [];

        foreach ($this->keywords() as $keyword) {
            foreach ($this->tsDefinitionsFor($keyword) as $defName => $defBody) {
                $definitions[$defName] = $defBody;
            }
            $members[$this->keywordString($keyword)] = $this->tsTypeFor($keyword);
        }

        ksort($definitions);
        ksort($members);

        $out = "// Generated by `php artisan composition:export-grammar` — do not hand-edit.\n\n";

        foreach ($definitions as $body) {
            $out .= $body."\n\n";
        }

        $out .= "export interface GenerationGrammarKeywords {\n";
        foreach ($members as $name => $type) {
            $out .= "  '{$name}'?: {$type};\n";
        }
        $out .= "}\n";

        return $out;
    }

    /**
     * @return list<GenerationKeyword>
     */
    private function engineAndBaseKeywords(): array
    {
        return [
            new GenerationKeyword(
                accessor: 'maxDepth',
                source: ValueSource::Integer,
                description: 'Caps the recursion depth of grammar expansion at this subtree root; the interpreter clamps the effective depth to the engine cap and demotes an expandable beat at the ceiling. Read-side only — no attribute emits it.',
            ),
            new GenerationKeyword(
                accessor: 'dereference',
                source: ValueSource::Text,
                description: 'Base-owned, unprefixed dispatch handle (like $ref): names the Dereferencer that resolves this node. Shared across engines; canonical home is the laravel-json-reference leaf.',
            ),
        ];
    }

    private function keywordString(GenerationKeyword $keyword): string
    {
        $accessor = $keyword->accessor;

        return $this->vocab->{$accessor}();
    }

    /**
     * @return array<string, mixed>
     */
    private function jsonSchemaFor(GenerationKeyword $keyword): array
    {
        return match ($keyword->source) {
            ValueSource::Enum => ['type' => 'string', 'enum' => $this->enumValues($keyword)],
            ValueSource::Union => $this->unionSchema($keyword),
            ValueSource::Boolean => ['type' => 'boolean'],
            ValueSource::Integer => ['type' => 'integer'],
            ValueSource::Text => ['type' => 'string'],
            ValueSource::Object_ => $this->objectSchema($keyword),
        };
    }

    private function tsTypeFor(GenerationKeyword $keyword): string
    {
        return match ($keyword->source) {
            ValueSource::Enum, ValueSource::Object_ => $this->namedTsType($keyword),
            ValueSource::Union => $this->unionTsType($keyword),
            ValueSource::Boolean => 'boolean',
            ValueSource::Integer => 'number',
            ValueSource::Text => 'string',
        };
    }

    private function namedTsType(GenerationKeyword $keyword): string
    {
        return $keyword->tsType ?? throw new RuntimeException("Keyword [{$keyword->accessor}] needs a tsType for its named TypeScript projection.");
    }

    /**
     * @return array<string, string>
     */
    private function tsDefinitionsFor(GenerationKeyword $keyword): array
    {
        if ($keyword->source === ValueSource::Enum) {
            $name = $this->namedTsType($keyword);
            $union = implode(' | ', array_map(
                fn (string $value): string => "'{$value}'",
                $this->enumValues($keyword),
            ));

            return [$name => "export type {$name} = {$union};"];
        }

        if ($keyword->source === ValueSource::Object_) {
            $name = $this->namedTsType($keyword);
            $lines = [];
            foreach ($this->objectProperties($keyword) as $property => [$jsonType, $tsType, $required]) {
                $optional = $required ? '' : '?';
                $lines[] = "  {$property}{$optional}: {$tsType};";
            }

            return [$name => "export interface {$name} {\n".implode("\n", $lines)."\n}"];
        }

        return [];
    }

    /**
     * @return list<string>
     */
    private function enumValues(GenerationKeyword $keyword): array
    {
        $class = $keyword->sourceClass ?? throw new RuntimeException("Enum keyword [{$keyword->accessor}] declares no source enum.");

        return array_map(
            fn (\BackedEnum $case): string => (string) $case->value,
            $class::cases(),
        );
    }

    /**
     * @return array<string, mixed>
     */
    private function unionSchema(GenerationKeyword $keyword): array
    {
        return ['oneOf' => array_values(array_map(
            fn (string $type): array => $this->scalarJsonType($type),
            $this->unionMemberTypes($keyword),
        ))];
    }

    private function unionTsType(GenerationKeyword $keyword): string
    {
        return implode(' | ', array_map(
            fn (string $type): string => $this->scalarTsType($type),
            $this->unionMemberTypes($keyword),
        ));
    }

    /**
     * @return list<string>
     */
    private function unionMemberTypes(GenerationKeyword $keyword): array
    {
        $class = $keyword->sourceClass ?? throw new RuntimeException("Union keyword [{$keyword->accessor}] declares no source class.");
        $method = $keyword->sourceMethod ?? throw new RuntimeException("Union keyword [{$keyword->accessor}] declares no source method.");

        $returnType = (new ReflectionMethod($class, $method))->getReturnType();

        if ($returnType instanceof ReflectionUnionType) {
            return array_map(
                fn (ReflectionNamedType $t): string => $t->getName(),
                array_filter(
                    $returnType->getTypes(),
                    fn ($t): bool => $t instanceof ReflectionNamedType,
                ),
            );
        }

        if ($returnType instanceof ReflectionNamedType) {
            return [$returnType->getName()];
        }

        throw new RuntimeException("Union keyword [{$keyword->accessor}] source method has no reflectable return type.");
    }

    /**
     * @return array<string, mixed>
     */
    private function objectSchema(GenerationKeyword $keyword): array
    {
        $properties = [];
        $required = [];

        foreach ($this->objectProperties($keyword) as $property => [$jsonType, $tsType, $isRequired]) {
            $properties[$property] = $jsonType;
            if ($isRequired) {
                $required[] = $property;
            }
        }

        $schema = ['type' => 'object', 'properties' => $properties];
        if ($required !== []) {
            $schema['required'] = $required;
        }

        return $schema;
    }

    /**
     * Reflect a keyword's source constructor into `property => [jsonSchema, tsType, required]`. A parameter is
     * required when its type is neither nullable nor an array (the emitted keyword filters out null/empty).
     *
     * @return array<string, array{array<string, mixed>, string, bool}>
     */
    private function objectProperties(GenerationKeyword $keyword): array
    {
        $class = $keyword->sourceClass ?? throw new RuntimeException("Object keyword [{$keyword->accessor}] declares no source class.");

        $constructor = (new \ReflectionClass($class))->getConstructor();
        if ($constructor === null) {
            return [];
        }

        $out = [];

        foreach ($constructor->getParameters() as $parameter) {
            $type = $parameter->getType();
            $typeName = $type instanceof ReflectionNamedType ? $type->getName() : 'mixed';
            $required = ! $this->parameterIsOptionalInKeyword($parameter, $typeName);

            $out[$parameter->getName()] = [
                $this->scalarJsonType($typeName),
                $this->scalarTsType($typeName),
                $required,
            ];
        }

        return $out;
    }

    private function parameterIsOptionalInKeyword(ReflectionParameter $parameter, string $typeName): bool
    {
        $type = $parameter->getType();

        if ($type !== null && $type->allowsNull()) {
            return true;
        }

        // Array-valued keyword parts are dropped when empty, so they are never guaranteed present.
        return $typeName === 'array';
    }

    /**
     * @return array<string, mixed>
     */
    private function scalarJsonType(string $type): array
    {
        return match ($type) {
            'string' => ['type' => 'string'],
            'int' => ['type' => 'integer'],
            'float' => ['type' => 'number'],
            'bool' => ['type' => 'boolean'],
            'array' => ['type' => 'array'],
            'null' => ['type' => 'null'],
            default => throw new RuntimeException("Cannot project non-scalar keyword value type [{$type}] to JSON Schema."),
        };
    }

    private function scalarTsType(string $type): string
    {
        return match ($type) {
            'string' => 'string',
            'int', 'float' => 'number',
            'bool' => 'boolean',
            'array' => 'unknown[]',
            'null' => 'null',
            default => throw new RuntimeException("Cannot project non-scalar keyword value type [{$type}] to TypeScript."),
        };
    }
}
